name: chore_manager_mobile
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+93929214

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  get: ^4.6.1
  http: ^1.1.0
  intl: ^0.18.0

dev_dependencies:
  faker: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
