name: Deploy to Stores
on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: macos-13
    environment: production
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
      APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{ vars.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64 }}
      FASTLANE_GITHUB_PAT: ${{ secrets.FASTLANE_GITHUB_PAT }}
      USERNAME: ${{ secrets.USERNAME }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
        channel: stable

    - name: Get Packages
      run: flutter pub get

    - name: Deploy to App Store
      run: bundle exec fastlane ios deploy
